### PR TITLE
Update the "data" node in app metadata

### PR DESCRIPTION
**Pull request by ChrisCoffey**
The current code updates the root of the app_metadata rather than the `data` node. This just nests the update down properly.

Please squash merge this.

### CODE REVIEW

**Comment by ChrisCoffey** [comment]
@ralphmorton please merge. 

Sorry about the extra commits, they've already landed so just a single-line diff.

**Comment by ralphmorton** [comment]
There appears to be a typo in the commit:

`a0Req pATCH`

EDIT: @ChrisCoffey - just realized I should probably tag you so you see this!

**Comment by ChrisCoffey** [comment]
Actually, that's not a typo. Perhaps you can educate me on how to factor out the `CustomMethod PATCH` into something i can use as an `HttpMethod` w/o Haskell thinking my new function is a data constructor?

**Comment by ralphmorton** [comment]
@ChrisCoffey Ah, I see! My apologies, I just looked at the commit snippet rather than the whole file. I don't think there is any way to stop Haskell from treating an uppercase-prefixed term as a constructor at value level. I will squash merge this now.

**Pull request merged**
